title: "Rohan Sen"
title_separator: ""     # prevents "Page | Site" patterns
description: "PhD in Econometrics and Statistics at USI Lugano. Research in kernel methods, financial econometrics, statistical learning."
url: "https://rohansen-8.github.io"
baseurl: ""     # important for user sites
theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

author:
  name: "Rohan Sen"

profile_picture: assets/img/photo.jpeg
